server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fastesttyper?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: fastesttyper
    password: typerpass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: never
  rabbitmq:
    host: localhost
    stomp:
      port: 61613
    username: guest
    password: guest
secretToken: secreto
